name: Portfolio Deployment to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -x
            mkdir -p ~/app
            cd ~/app
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/Amritakastwar/Portfolio.git .
            fi
            docker-compose down || true
            docker-compose up -d --build
          EOF
